name: flutter_stopwatch_app
description: "Flutter stopwatch app assignment featuring start/pause/reset controls, real-time elapsed time, lap recording, and an analog clock UI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.8
  fake_async: ^1.3.3
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^2.6.1
  logger: ^2.6.2
  shared_preferences: ^2.5.3
  one_clock: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.7.0
  freezed: ^3.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: GoogleSansFlex
      fonts:
        - asset: assets/fonts/google_sans_flex.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#52AE31"
    theme_color: "#52AE31"

flutter_native_splash:
  color: "#52AE31"
  image: assets/icon/app_icon.png
  branding_bottom_padding: 24
  color_dark: "#52AE31"
  image_dark: assets/icon/app_icon.png

  android_12:
    image: assets/icon/app_icon.png
    icon_background_color: "#52AE31"
    image_dark: assets/icon/app_icon.png
    icon_background_color_dark: "#52AE31"

  web: true

